export const APP_ACTIONS = {
    SET_WEATHER_INFO: 'SET_WEATHER_INFO',
    SET_WEATHER_FORECAST: 'SET_WEATHER_FORECAST',
    FETCH_WEATHER_INFO: 'FETCH_WEATHER_INFO',
    WEATHER_INFO_SUCCESS: 'WEATHER_INFO_SUCCESS',
    WEATHER_INFO_ERROR: 'WEATHER_INFO_ERROR'
}